### PR TITLE
Uncontroversial indentation fixes

### PR DESCRIPTION
**Pull request by mk-pmb**
Intentation survey for master:
390 lines in 15 files are indented with tabs only.
1519 lines in 48 files are indented with spaces only.
244 lines in 3 files have mixed indentation.
16 lines in 6 files have trailing whitespace.
11 files use multiple styles of indentation.

Intentation survey after this PR:
158 lines in 12 files are indented with tabs only.
1993 lines in 48 files are indented with spaces only.
0 lines in 0 files have mixed indentation.
0 lines in 0 files have trailing whitespace.
8 files use multiple styles of indentation.

… so I suggest as the next step we normalize to spaces.

### CODE REVIEW

**Comment by mk-pmb** [comment]
I wondered why so few lines were indented at all. There was a bug in counting. I updated the numbers.

**Comment by adrian15** [comment]
> … so I suggest as the next step we normalize to spaces.

Yes, please normalize to two-spaces width indentation.
Thank you.

**Comment by adrian15** [comment]
Any progress on normalizing to two-spaces width identation?

I would like to have this pull request applied before working on https://github.com/supergrub/supergrub/issues/51 and other fixes.

Thank you.

**Comment by mk-pmb** [comment]
Oh ok, I'll priorizize it then. Had it on low prio because I thought SGD was on hiatus. :)

**Comment by adrian15** [comment]
> Oh ok, I'll priorizize it then. Had it on low prio because I thought SGD was on hiatus. :)

Yeah, it's sort of frozen because I'm focusing on Rescatux/Rescapp.
I'm worried about being blocked because of your unfinished work in, I don't know, two months time.

So... there's no rush but don't forget about it.

**Comment by adrian15** [comment]
> Update: Some of the bash scripts are so broken and brittle, we should fully rewrite them some day.

Feel free to file any bugs you find as new issues.

**Comment by mk-pmb** [comment]
While trying to backport e9317f8e4a73e3200661d5e94284db43b1fd727d ("Disk and partitions: Handle empty label properly."), I wonder about the logic. Wouldn't it be easier to just set label to empty string just before `probe -s label -l $dev`? We should probably do that for all the probe variables, so they won't silently keep their old value if the probe fails for any strange reason.
Also is there a reason for the negated emptiness-check `if [ ! -z $label ]`? Otherwise I'd suggest we check for non-emptiness, and also quote the var: `if [ -n "$label" ]`

**Comment by mk-pmb** [comment]
I'll just backport it verbatim for now, so we can get this merged asap and not accumulare more merge conflicts.

**Comment by adrian15** [comment]
> I'll just backport it verbatim for now, so we can get this merged asap and not accumulare more merge conflicts.

Yeah, keep this pull request only about whitespaces. Later on you might want to open a new issue with that discussion about _Disk and partitions: Handle empty label properly_ backport that you brought in.

**Comment by mk-pmb** [comment]
All the whitespace fixes are done. What's left to do so we can merge? If you compare with `--ignore-all-space`, code review should be trivial. ;-)

**Comment by adrian15** [comment]
Any reason why grub-build-001-prepare-build and alike files have not been also translated to two-space identation?

**Comment by mk-pmb** [comment]
I had a filter on filename extensions, because some formats (like Makefiles) require tabs. I'll detect by shebang line also and transform them.

**Comment by mk-pmb** [comment]
No more results for `git grep -Pe '^\t'`, so I guess I found all. :-)

**Pull request merged**
