### PR TITLE
Show boot mode in main menu #58

### LINKED ISSUE #58: Show boot mode in main menu
Hi! I want to see if I booted in EFI or legacy mode, so I'll run "Detect and show boot methods" and it will take some long time. Which inspired me: Can we show the boot mode right in that menu item?

Update: Patch in progress.

### PR DESCRIPTION
**Pull request by mk-pmb**
Fixes #58

### CODE REVIEW

**Comment by mk-pmb** [comment]
What's left to do?

**Comment by adrian15** [comment]
> What's left to do?

As I said in the original issue I want to integrate this functionality myself into SG2D because of the upcoming Secure Boot integration.

There are two concerns about this functionality that I have myself while planning to implement it in the future:

- The Secure Boot integration (Not only showing if UEFI SecureBoot is on but also if it's the Debian one or the Ubuntu one).
- The variable should be only set once when SG2D main menu is loaded for the first time (not every time the main menu is loaded).

Now that I check your commit you are adding it on an option (Boot manually).
My implementation would add it as a main menu title or as a main menu subtitle.

However I encouraged in the former issue to implement it so that I did not have to implement it from scratch. So thank you.

**Comment by mk-pmb** [comment]
Depending on how long you take for your version, could you maybe merge this one and later replace it? That way I wouldn't need to re-merge it in my version each time I pull your master.

**Comment by mk-pmb** [comment]
Solved. The commands is `source`, no idea why I thought `include`.

**Comment by mk-pmb** [comment]
Any news on this?

**Comment by adrian15** [comment]
Not sure if this is going to final commit which will make it to the main branch but this has been already done in: https://github.com/supergrub/supergrub/commit/a7fa173f24fbf40e029923ad57583bf2b39c6bad so... I'm going to close this pull request.

Your work was very helpful so Thank you very much!

**Pull request closed without merging**
