### PR TITLE
2.06s3 dev23

### PR DESCRIPTION
**Pull request by thermon**
autoiso.cfg and grubdetect.cfg modified for btrfs.
diskpartchainboot.cfg modified.

### CODE REVIEW

**Comment by thermon** [comment]
diskpartchainboot.cfg, autoiso.cfg, and grubdetect.cfg modified.

**Comment by thermon** [comment]
I tried grouping the boot entries of osdetect,cfg.
I think it's easier to understand now that the file system label is displayed.
IMG20240615154756 (1)

**Comment by adrian15** [comment]
Would you please use spaces instead of tabs for your next contributions?

Thank you!

**Comment by adrian15** [comment]
Also don't add your custom changes to _automatic-builder.Dockerfile_ into your pull requests.

**Comment by adrian15** [comment]
Thank you for your work.
I have merged some of your BTRFS work manually.
The entry grouping part is nice but I'm going to do it in another way.

Closing the pull request.

**Pull request closed without merging**
