### PR TITLE
root patition & boot patition relation by filesystem label

### PR DESCRIPTION
**Pull request by thermon**

### CODE REVIEW

**Comment by adrian15** [comment]
```
if test $root_label = $fstab_label;then
```

Well, when you have a /boot partition it has the kernel and initrd and you might have a label that it's completely different than the / partition label which will have the rest of the system with an empty /boot directory.

So there is no need to compare one label to another label because most of the times they aren't going to be similar. Also most of times the filesystem label might be unset.

Assuming I have understood what your pull request does I'm not sure how this is useful in a real life scenario.

**Comment by thermon** [comment]
The file system label is used to tell sg2d to the distro and partition role, so you need to change it accordingly.

**Comment by adrian15** [comment]
> The file system label is used to tell sg2d to the distro and partition role, so you need to change it accordingly.

That's not necessarily true.

Maybe you can share with us an screenshot before using your pull request, another screenshot after using your pull request. Describe what's wrong in the first screenshot and what your pull request fixes so that it's not wrong anymore.

Otherwise I'm afraid I'm not understanding the usefulness of this pull request.

**Comment by thermon** [comment]
This is before commit
This is the execution content of osdetect-linux-boot.cfg.
The boot partitions "xubuntu:boot" and "ubuntu:boot" are associated with the root partition "ubuntu".

20240703091454_p

**Comment by thermon** [comment]
This is the screen after committing.
"ubuntu" to "ubuntu:boot" and  "xubuntu" to "xubuntu:boot" correspond, respectively.
IMG20240703093304

**Comment by adrian15** [comment]
Well, given one distro before your patch you could select 4 different kernels and after your patch you can select 2 different kernels.

That's not right.

You should be able to select any kernel as long as it's inside a /boot partition or btrfs volume inside a /boot partition.

And even if this was a good idea you cannot rely on filesystem labels because you cannot rely on them being set in the first place.

**Comment by thermon** [comment]
Of the 4 pre-patch kernels, the previous 2 kernels are loading the wrong partition. 

Correlation using file system labels is a last resort as there is little information that grub can handle.
 If grub can read /etc/fstab and get the device name, there is no need to do this.

**Comment by adrian15** [comment]
> Of the 4 pre-patch kernels, the previous 2 kernels are loading the wrong partition.


Ok.
 
> Correlation using file system labels is a last resort as there is little information that grub can handle.

Yeah, but no need to make this more complex.

>  If grub can read /etc/fstab and get the device name, there is no need to do this.

One should create such a module send it to upstream grub and then convince Debian/Ubuntu guys that it's a good idea to have that module in Secure Boot builds. Even if it would be fun to learn how to build such that grub module I'm not going to do that.

**Pull request closed without merging**
