### PR TITLE
set root for subvol matching

### PR DESCRIPTION
**Pull request by thermon**

### CODE REVIEW

**Comment by adrian15** [comment]
> set root=$cfg_device

That's not right.

root variable should only be modified in the menuentry itself and that's what we are already doing.
Otherwise if go back root variable is being changed and the SG2D's own Grub cannot find their own modules.

**Comment by adrian15** [comment]
In osdetect.cfg there is no need of setting root variable because in the for loop we already have `($device)` in it.

```
for file in ($device)${bootdir}/vmlinuz-* ($device)${bootdir}/linux-* ($device)${bootdir}/kernel-genkernel-*; do
```

**Comment by adrian15** [comment]
This part:
```
for grubdir in /grub /grub2 /boot/grub /boot/grub2; do
```
regarding cfgdetect.cfg and cfgextract.cfg, yes, that's probably something that needs to be fixed.

Thank you!

**Comment by thermon** [comment]
Finally, I was able to recognize BTRFS subvolumes without using set root.
The variables in osdetect.cfg are a bit complicated.

**Comment by thermon** [comment]
just renamed $subvol to $subvolpath

**Comment by thermon** [comment]
My cfg file is working fine as in these pictures.

20240607171256_p
20240607171341_p

**Comment by adrian15** [comment]
Partially integrated on https://github.com/supergrub/supergrub/tree/2.06s3-dev23 .

**Pull request closed without merging**
